str(input("Cree una cuenta con su correo electronico"))
correoelectronico=str(input())
str(input("Digite su nombre"))
nombre=str(input())
int(input("Digite su nombre"))
edad=int(input())
str(input("Digite su numero de tarjeta de credito"))
tarjeta_credito=int(input())

str(input("Modifique su informacion personal"))
informacion_personal=str(input())
str(input("Modifique el numero de su tarjeta bancaria"))
numero_tarjetadecredito=int(input())
str(input("Por sus compras realizadas acumula puntos, por las cuales puede canjear premios fisicos"))
canje_puntos=int(input())
